name: Deploy Aiogram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodni yuklash
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Serverga ulanish va fayllarni yuklash
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Agar botcicd papkasi mavjud bo'lmasa, uni klon qilamiz
            if [ ! -d "~/botcicd" ]; then
              git clone https://github.com/themusharraf/botcicd.git
            fi
            cd ~/botcicd
       
            # Virtual muhitni yaratish yoki mavjud bo'lsa faollashtirish
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate

            # Kutubxonalarni o'rnatish
            pip install --upgrade pip
            pip install -r requirements.txt

            # Botni qayta ishga tushirish
            pkill -f "python.*main.py" || true
            nohup venv/bin/python main.py > bot.log 2>&1 &
